### ISSUE TITLE
This plugin will cause the right-click "Mask Editor" to disappear

### ISSUE THREAD

**Issue by laidingq** [MokkaBoss1/ComfyUI_Mokkaboss1#2]
This plugin will cause the right-click "Mask Editor" to disappear

**Comment by MokkaBoss1** [comment]
Hi thanks for raising an issue. Any chance you could provide a few more details to help me solve the issue?

I have the node suite implemented and am still able to use the mask editor.

thanks

**Comment by laidingq** [comment]
Sorry, I need to double check which plugin caused the problem
